name: Publish AWS Lambda Layer Version

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  deploy:
    needs: build
    strategy:
      fail-fast: true

  update_readme:
    needs: deploy
